# death-penalty 用 fail2ban フィルタです。再犯が続く IP アドレスを長期間遮断します。
#
# recidiveジェイルでのBANを検知するフィルタ

[Definition]

_daemon = fail2ban\.actions

# 検知条件: recidive ジェイルでの BAN を検知します。
# 例: 2026-02-04 15:18:28,240 fail2ban.actions        [1]: NOTICE  [recidive] Ban 102.244.97.183
failregex = ^.* fail2ban\.actions\s+\[.*\]:\s*NOTICE\s+\[recidive\]\s+Ban\s+<HOST>\s*$

# 除外条件:
ignoreregex = 
