# Fail2Ban filter for death-penalty (Long term ban for recidivists)
#
# recidiveジェイルでのBANを検知するフィルタ

[Definition]

_daemon = fail2ban\.actions

# Failregex: recidiveジェイルでのBANを検知
# 例: 2026-02-04 15:18:28,240 fail2ban.actions        [1]: NOTICE  [recidive] Ban 102.244.97.183
failregex = ^.* fail2ban\.actions\s+\[.*\]:\s*NOTICE\s+\[recidive\]\s+Ban\s+<HOST>\s*$

# Ignoreregex: 
ignoreregex = 
