[Definition]
failregex = ^<HOST> .* ".* (/(wp-login\.php|xmlrpc\.php|wp-admin|wp-config\.php|wp-cron\.php|wp-json|\.env|\.git|vendor/phpunit|phpinfo\.php|\.DS_Store|\.vscode|composer\.(json|lock)|\.well-known/acme-challenge/[^ ]*|/boaform|/HNAP1/|/hudson|/jenkins|/id_rsa|/server-status))[^ ]* HTTP/[^"]*" [0-9]{3} [0-9]+
ignoreregex = .* ".* /wp-login\.php.*login_18730.* HTTP/[^"]*" [0-9]{3} [0-9]+|.* ".* /wp-login\.php.* HTTP/[^"]*" [0-9]{3} [0-9]+ ".*login_18730.*"
