[Definition]
failregex = ^<HOST> - - \[.*\] "PROPFIND / HTTP/.*"
            ^<HOST> - - \[.*\] "POST /wp-login\.php HTTP/.*" (200|401|403)
            ^<HOST> - - \[.*\] "GET /.env HTTP/.*"
            ^<HOST> - - \[.*\] ".*" \d+ \d+ "-" ".*(bingbot|zgrab|l9explore|Googlebot).*"
ignoreregex =
