[Definition]
failregex = ^<HOST> - - \[.*\] "PROPFIND / HTTP/.*"
            ^<HOST> - - \[.*\] "GET /(\.env|config\.env|wp-config\.php(?:\.bak)?|\.git/config) HTTP/.*"
            ^<HOST> - - \[.*\] "GET /cgi-bin/.* HTTP/.*"
            ^<HOST> - - \[.*\] "GET /manager/html HTTP/.*"
            ^<HOST> - - \[.*\] "POST /xmlrpc\.php HTTP/.*" .*
            ^<HOST> - - \[.*\] "POST /wp-login\.php HTTP/.*" .*
            ^<HOST> - - \[.*\] ".*" \d+ \d+ "-" ".*(zgrab|l9explore|bingbot|OAI-SearchBot|Googlebot-Image).*"
ignoreregex =
